README.md, docs/index.md
Ajustando detalhes do readme/docs
=> Ajustando detalhes do readme/docs

docs/modelagem/requisitos.md, docs/sprints/sprint3/reuniao.md, mkdocs.yml
#7 Neste documento, apresentamos os requisitos propostos para a elaboração do pipeline, que desempenhará um papel fundamental no garantir um bom funcionamento do produto final. O pipeline é uma estrutura crucial para o fluxo contínuo de dados e informações dentro do sistema, permitindo a automatização de processos, a integração de diferentes componentes e a otimização do fluxo de trabalho.
=> Adição dos requisitos funcionais

docs/reunioes/reuniao1/reuniao.md, docs/reunioes/reuniao2/acompanhamento.md, docs/reunioes/reuniao3/reuniao.md, docs/reunioes/reuniao4/reuniao.md, docs/reunioes/reuniao5/reuniao.md, docs/reunioes/reuniao6/reuniao.md, mkdocs.yml
=> Reunião semana 6

docs/reunioes/reuniao7/reuniao.md, docs/reunioes/reuniao7/reuniao7.md, mkdocs.yml
Adição do que foi discutido na reunião do dia 03/08
=> #35 Adicionando Atas da Reunião de Abertura da Sprint 7

docs/modelagem/prototipo.md, mkdocs.yml
Para atender aos requisitos do projeto, foi realizado um protótipo detalhado no Figma.
- #39 
O que foi concluído até o momento.
Link do protótipo Figma: https://www.figma.com/file/xmJPF6GeLhiM6jleXKuTcW/Untitled?type=design&node-id=0%3A1&mode=design&t=ZjK5V7ChA4udlg6U-1
=> Adicionando protótipo da Dashboard

docs/dashboards/dashboards.md, mkdocs.yml
Adiciona um arquivo relacionado a empregabilidad por setor ao powerBi
=> #30 Postando link PowerBi Empregabilidade do Setor

docs/cronograma/roadmap.md, mkdocs.yml
Realizar o desenho do roadmap do projeto até a entrega final
- #53 
O que foi concluído até o momento.
=> Add product roadmap

docs/dashboards/dashboards.md
Adicionando tabelas os gráficos e fonte de dados
Aba responsável por inserir as demandas desta issue.
=> Adicionando tabelas de dados aos indicadores

docs/elicitacao/entrevista.md
A técnica de elicitação de requisitos por meio de entrevistas é uma abordagem utilizada para coletar informações detalhadas diretamente dos stakeholders do projeto. Essa técnica envolve uma interação direta entre o analista de requisitos e os stakeholders, permitindo uma compreensão mais profunda das necessidades, desejos, expectativas e restrições que envolvem o sistema a ser desenvolvido.
=> Entrevista

docs/elicitacao/priorizacao/MoScoW.md, docs/modelagem/agil/backlog.md, mkdocs.yml
Priorização, refere-se ao processo de avaliar e classificar os requisitos de um projeto de acordo com sua importância e urgência. Essa atividade é crucial para garantir que os recursos limitados sejam alocados de maneira eficaz e que as funcionalidades mais valiosas sejam implementadas primeiro. A priorização ajuda a equipe a tomar decisões informadas sobre o que desenvolver primeiro, alocando tempo e recursos de maneira estratégica.
=> Priorizacao moScoW

README.md, docs/index.md
Necessário atualização do readme
=> Atualizando o readme

README.md, docs/analise/rich_picture.md, docs/modelagem/agil/backlog.md, mkdocs.yml
Adicionando o Rich Picture
O richpicture é uma técnica visual usada principalmente na engenharia de requisitos para capturar de maneira gráfica e ilustrativa a complexidade e a interação entre diferentes elementos de um sistema, processo ou situação. O rich picture é uma técnica flexível que pode ser adaptada para diferentes contextos e projetos. Ele pode ser usado como ponto de partida para análise mais detalhada.
<div align="center">
</div>
=> Rich ricture

04_PipelineTCU/constants/Cenarios_PNE/AtendPontaPNE.csv, 04_PipelineTCU/constants/Cenarios_PNE/ConsGasNatPNE.csv, 04_PipelineTCU/constants/Cenarios_PNE/CustoTotPNE.csv, 04_PipelineTCU/constants/Cenarios_PNE/EmTotPNE.csv, 04_PipelineTCU/constants/Cenarios_PNE/GerPerMedPNE.csv, 04_PipelineTCU/constants/Cenarios_PNE/PotAcumPNE.csv, 04_PipelineTCU/pne_proc.py
Correção da ordenação dos caracteres para UTF-8 no código e nas tabelas. Em seguida, vou passar as tabelas para o banco.
=> (#160) Correção da ordenação dos caracteres para UTF-8

docs/dashboards/dashboards.md, docs/fonte_dados/fonte_dados.md, docs/modelagem/agil/backlog.md, mkdocs.yml
Corrigindo formatação e links do gitpages
=> Fix documentacao

docs/comunicacao/documentacao_sprints/sprint10.md, docs/comunicacao/documentacao_sprints/sprint11.md, docs/comunicacao/documentacao_sprints/sprint12.md, docs/comunicacao/documentacao_sprints/sprint13.md, mkdocs.yml
Adições:
- Documentação das Sprints 10, 11, 12 e 13;
- Documentação das Sprints adicionadas ao mkdocs.
=> Documentação das Sprints 12 e 13

README.md, docs/pipeline/pipeline.md, mkdocs.yml
Adicionando ETL do pipeline de dados, e atualizando tecnologias do readme.
<table border="0">
<tr>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
<td>
</a>
</td>
</tr>
<tr>
<td>Microsoft Azure</td>
<td>Data Factory</td>
<td>SQL Server</td>
<td>Power Bi</td>
</tr>
</table>
<p align="center">
</p>
=> Atualizando tecnologias

docs/dashboards/dashboards.md
Foram adicionados as visualizações das emissões de GEE do Brasil
=> Adicionando Emissões GEE Brasil

docs/dashboards/dashboards.md
Esta issue foi formulada a partir de uma reunião com o TCU, em que foi citado a necessidade de exibir as informações da evolução das diferentes fontes de tecnologia desde 1990.
=> Adicionando Evolução do uso das tecnologias 1970 - 2022

README.md, docs/painel/painel.md, mkdocs.yml
Este PR tem o objetivo de publicar o acesso ao painel do Power Bi, possibilitando um fácil acesso aos visitantes do repositório
- #131 
- #174
=> Publicando painel

docs/painel/painel.md
Esta issue tem o objetivo de publicar o acesso ao painel do Power Bi, possibilitando um fácil acesso aos visitantes do repositório
=> Atualizando tamanho do painel

04_PipelineTCU/epe_matriz.py
Esse script tem o objetivo de fazer a extração da fonte de dados e carregar no repositório arquivo de forma automática. O nome do arquivo deve ser o mesmo que estará configurado no Azure (RAW). O github realiza a ação de transformar o arquivo .xlsx em um dataframe que será consumido pelo Pipeline da Azure.
=> Automação de extração e upload no git

docs/tutoriais/tutoriais.md, mkdocs.yml
Neste documento apresentaremos os treinamentos que foram desenvolvidos para a equipe com o propósito de capacitar os membros no uso do SQL Server, Azure e na manipulação de dados. Tanto para os novos membros da equipe como para aqueles que buscam aprimorar suas habilidades, os tutoriais reduzem a curva de aprendizado. Eles fornecem orientações passo a passo sobre como realizar as tarefas do ETL, acelerando a adaptação e a eficácia da equipe.
=> Adicionando vídeo tutoriais do projeto

.github/workflows/atualiza_tabelas.yml, 04_PipelineTCU/main.py
Descomentando main.py e alterando atualiza_tabelas.yml para rodar script main
=> Testando git actions
